package com.leetcode.strings;

import java.util.ArrayList;
import java.util.List;

/**
 * https://www.geeksforgeeks.org/print-subsequences-string/
 * <p>
 * Given a string, we have to find out all subsequences of it.
 * A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
 * <p>
 * Input : abc
 * Output : a, b, c, ab, bc, ac, abc
 * <p>
 * Input : aaa
 * Output : a, aa, aaa
 */
public class _013_PrintAllSubsequenceOfStrings {

    public static void main(String[] args) {
        String word = "abc";
        System.out.println(printAllSubsequenceOfStrings(word));
    }

    private static List<String> printAllSubsequenceOfStrings(String word) {
        List<String> res = new ArrayList<>();
        int numberOfSubsequence = (1 << word.length()) - 1;
        for (int i = 1; i <= numberOfSubsequence; i++) {
            StringBuilder currWord = new StringBuilder();
            for (int num = 0; num < word.length(); num++) {
                if ((i & (1 << num)) != 0) {
                    currWord.append(word.charAt(num));
                }
            }
            res.add(currWord.toString());
        }
        return res;
    }
}
